= Grundlagen und verwandte Arbeiten <sec:relatedwork>

Die in dieser Arbeit entwickelte Middleware baut auf bekannten Ansätzen für entfernte Aufrufe und für die Kommunikation in verteilten und eingebetteten Systemen auf. Die ersten drei Abschnitte führen die Begriffe ein, die in den Entwurfskapiteln benötigt werden. Anschließend wird die eigene Lösung in dieses Umfeld eingeordnet. Da das Feld sehr breit ist, werden ausgewählte Vertreter betrachtet und anhand einheitlicher Kriterien verglichen. Ziel ist es, die Lücke zu benennen, die die vorliegende Arbeit schließt.

== Entfernter Prozeduraufruf und Middleware <sec:grundlagen-rpc>

Bei einem entfernten Prozeduraufruf, englisch @rpc, ruft ein Programm eine Prozedur auf, die auf einem anderen Rechner ausgeführt wird. Im Quelltext sieht dieser Aufruf wie ein gewöhnlicher lokaler Aufruf aus. Die Idee wurde von Birrell und Nelson beschrieben und bildet seitdem die Grundlage der meisten Middleware-Systeme @ImplementingRemoteProcedure1984. Der Aufruf wird auf der aufrufenden Seite von einem Stellvertreter entgegengenommen, der dieselbe Signatur besitzt wie die eigentliche Prozedur, sie aber nicht ausführt. Er verpackt den Namen der Prozedur und die Argumente zu einer Nachricht und übergibt sie dem Transport. Auf der ausführenden Seite nimmt ein Gegenstück die Nachricht entgegen, liest die Argumente aus, ruft die eigentliche Prozedur auf und schickt deren Rückgabewert zurück. Dieses Gegenstück wird klassisch als Skelett bezeichnet. Das Umwandeln von Argumenten und Rückgabewerten in eine übertragbare Form heißt Marshalling.

Das Ziel dieses Aufbaus ist die Aufrufstransparenz. Der Aufrufer soll nicht wissen müssen, ob eine Prozedur lokal oder entfernt ausgeführt wird. Vollständig erreichen lässt sich das allerdings nicht. Ein entfernter Aufruf dauert um Größenordnungen länger als ein lokaler, er kann teilweise fehlschlagen, während der Aufrufer weiterläuft, und Zeiger in den lokalen Speicher haben auf der Gegenseite keine Bedeutung. Waldo et al. zeigen, dass sich diese Unterschiede nicht dauerhaft verbergen lassen und in der Schnittstelle sichtbar bleiben sollten @NoteDistributedComputing. Transparenz wird deshalb meist als Aussage über die Aufrufsyntax verstanden und weniger als Zusicherung gleicher Laufzeiteigenschaften.

Die Schicht, die Stellvertreter, Marshalling und Transport bereitstellt, wird als Middleware bezeichnet. Sie liegt zwischen der Anwendung und der Verbindung, bietet der Anwendung eine einheitliche Schnittstelle an und verbirgt die Eigenheiten der Übertragung @DistributedSystems3rd. Ein häufig verwendeter Aufbau für solche Systeme ist das Broker-Muster. Es beschreibt den Stellvertreter auf der Client-Seite, den vermittelnden Broker und das Gegenstück auf der Server-Seite als eigenständige Rollen @PDFPatternorientedSoftware.

Der ursprüngliche Ansatz kennt nur einen festen Satz von Prozeduren. Objektorientierte Middleware erweitert ihn auf entfernte Objekte, die zur Laufzeit entstehen und über eine Referenz angesprochen werden. Der Stellvertreter entspricht dann dem Proxy-Muster @gammaDesignPatternsElements1995. Er implementiert dieselbe Schnittstelle wie das entfernte Objekt, führt dessen Referenz mit und gibt jeden Aufruf zusammen mit dieser Referenz weiter. Bekannte Vertreter dieses Ansatzes sind @corba @CommonObjectRequest und Java @rmi @JavaDevelopmentKit. Die Aufteilung in einen Stellvertreter auf der aufrufenden und ein Gegenstück auf der ausführenden Seite findet sich in @sec:architektur wieder, wo das Gegenstück als Adapter bezeichnet wird.

== Serialisierung von Nachrichten <sec:grundlagen-serialisierung>

Eine Nachricht liegt im Programm als strukturierter Wert vor, etwa als Objekt, als Liste oder als Abbildung. Übertragen wird dagegen eine Folge von Bytes. Die interne Darstellung eines Werts im Arbeitsspeicher lässt sich dafür nicht direkt verwenden, da sie Verweise enthält und von Wortbreite, Byte-Reihenfolge und Laufzeitumgebung abhängt. Serialisierung bezeichnet die Umwandlung eines strukturierten Werts in eine Bytefolge, Deserialisierung den umgekehrten Weg.

Die gebräuchlichen Formate unterscheiden sich vor allem in zwei Punkten. Der erste ist die Kodierung. Textbasierte Formate wie @json oder @xml sind ohne Werkzeuge lesbar und erleichtern damit die Fehlersuche, benötigen aber mehr Platz, weil Schlüssel und Strukturzeichen als Klartext mit übertragen werden. Binäre Formate stellen dieselben Werte deutlich kürzer dar, ihre Ausgabe ist ohne Kenntnis des Formats jedoch nicht mehr zu deuten. Der zweite Punkt ist die Bindung an ein Schema. Schemafreie Formate führen die Struktur in der Nachricht selbst mit, sodass Sender und Empfänger nichts vorab vereinbaren müssen. Schemagebundene Formate setzen eine geteilte Beschreibung der Datenstruktur voraus und sparen dafür die Feldnamen in der Nachricht ein. Welche Vertreter für ein Gerät mit sehr kleinen Paketen in Frage kommen, behandelt @sec:serialisierung-geraete.

Für diese Arbeit ist eine weitere Eigenschaft binärer Formate wichtig, denn ihre Ausgabe kann jedes beliebige Byte enthalten, auch das Nullbyte. Ein Empfänger kann die Länge der Nutzlast deshalb nicht aus dem Inhalt ableiten, etwa indem er Nullbytes am Ende eines Pakets als Füllung abschneidet, sodass die Rahmung die Länge ausdrücklich mitführen muss. Bei einem textbasierten Format fällt dieser Unterschied nicht auf, da dessen Ausgabe kein Nullbyte enthält, und er zeigt sich erst beim Wechsel auf eine binäre Kodierung. @sec:nutzlastlaenge greift das auf.

== Eingebettete Systeme und ihre Kommunikation <sec:grundlagen-embedded>

Eingebettete Systeme verfügen über erheblich weniger Speicher und Rechenleistung als ein Arbeitsplatzrechner. @rfc 7228 fasst solche Geräte unter dem Begriff constrained nodes zusammen und ordnet sie nach verfügbarem Arbeits- und Programmspeicher in Klassen ein @bormannTerminologyConstrainedNodeNetworks2014. Die betrachteten Größenordnungen liegen bei einigen zehn bis einigen hundert Kilobyte Arbeitsspeicher. In diesem Rahmen werden Entwurfsentscheidungen wichtig, die auf einem gewöhnlichen Rechner kaum eine Rolle spielen.

Auf solchen Geräten kommen angepasste Laufzeitumgebungen zum Einsatz, beispielsweise MicroPython als eine für Mikrocontroller ausgelegte Implementierung von Python @MicroPythonPythonMicrocontrollers. Der Sprachkern bleibt dabei weitgehend erhalten, während die Standardbibliothek stark verkleinert ist und ihr Umfang vom jeweiligen Port abhängt. Auf stark beschränkter Hardware fehlen zudem häufig ein vollständiger Netzwerkstack und die üblichen Mittel nebenläufiger Programmierung. Das ist kein Sonderfall einer einzelnen Firmware, sondern eine verbreitete Entwurfsentscheidung. Betriebssysteme für solche Geräte verzichten bewusst auf Threads je Aufgabe und arbeiten ereignisgetrieben, weil ein eigener Stack je Thread auf einem Gerät mit wenigen Kilobyte Arbeitsspeicher zu teuer ist @PDFSystemArchitecture @dunkelsContikiLightweightFlexible2004. Ohne Netzwerkstack stehen auch die darauf aufbauenden Abstraktionen von Sockets bis zu fertigen Protokollbibliotheken nicht zur Verfügung, und ohne Nebenläufigkeit gibt es keinen Hintergrundprozess, der Daten entgegennimmt, während die Anwendung weiterläuft. Hinzu kommt der kleine Heap, bei dem jede Zuweisung den Druck auf die Speicherbereinigung erhöht, weshalb Puffer nach Möglichkeit vorab angelegt und wiederverwendet werden.

Die Verbindung zwischen einem Mikrocontroller und seiner Peripherie erfolgt über Bussysteme, die für kurze Strecken und wenige Leitungen ausgelegt sind. Viele von ihnen arbeiten nach dem Master-Slave-Prinzip. Eine Seite, der Master, stößt jede Übertragung an, die andere Seite antwortet ausschließlich. @i2c @nxpI2CBusSpecification2021 und @spi @MctdeSPISerial2019 sind verbreitete Vertreter, auf Feldebene folgt Modbus im @rtu\-Modus demselben Muster @MODBUSApplicationProtocol. Ein Slave, bei dem Daten anfallen, kann diese nicht von sich aus schicken. Er hält sie bereit, bis der Master sie abfragt. Dieses wiederholte Abfragen wird als Polling bezeichnet. Wie schnell ein Ereignis auf der Slave-Seite beim Master ankommt, hängt damit vom Abfragetakt des Masters ab und nicht vom Zeitpunkt, an dem es entstanden ist.

Die je Übertragung nutzbare Datenmenge ist auf solchen Bussen klein und häufig fest vorgegeben. Die größte in einem Paket übertragbare Nutzlast wird als @mtu bezeichnet. Ist eine Nachricht länger, muss sie in mehrere Pakete zerlegt werden. Damit der Empfänger sie wieder zusammensetzen kann, trägt jedes Paket zusätzliche Steuerinformationen, die üblicherweise als Header vorangestellt werden. Diese Steuerinformationen gehen von der ohnehin knappen Nutzlast ab, sodass ihre Größe bei kleinen Paketen unmittelbar auf die Anzahl der nötigen Übertragungen durchschlägt. Wie sich diese Eigenschaften am betrachteten Zielsystem konkret darstellen, zeigt @sec:einschraenkungen.

== Einordnung und Auswahlkriterien

Für den Vergleich werden Kriterien herangezogen, die sich direkt aus den Rahmenbedingungen des Zielsystems ergeben. Das Zielsystem nutzt einen Master-Slave-Bus mit sehr kleinen, festen Paketen und läuft in stark eingeschränkten Laufzeitumgebungen.

Folgende Achsen werden betrachtet:

- *Abstraktionsgrad.* Bietet der Ansatz nur den Transport von Nachrichten, einen entfernten Prozeduraufruf oder darüber hinaus die Abstraktion entfernter Objekte?
- *Serialisierung.* Werden Daten textbasiert oder binär kodiert, und ist dafür ein vorab geteiltes Schema nötig?
- *Transportbindung.* Ist der Ansatz an einen konkreten Übertragungsweg gebunden oder von diesem unabhängig?
- *Fragmentierung.* Bringt der Ansatz Mechanismen für die Rahmung und das Zerlegen großer Nachrichten in kleine Pakete mit?
- *Eignung für einen Master-Slave-Bus.* Setzt der Ansatz voraus, dass die untergeordnete Seite eigenständig zustellen kann, oder kommt er mit einem rein anfragegetriebenen Kanal aus?
- *Ressourcenbedarf.* Lässt sich der Ansatz innerhalb der Grenzen von MicroPython und Pybricks betreiben?

Die betrachteten Ansätze liegen dabei nicht alle auf derselben Ebene, denn einige sind vollständige Rahmenwerke, andere beschränken sich auf die Beschreibung eines Nachrichtenformats, und wieder andere behandeln lediglich die Kodierung von Daten oder die Anbindung an einen bestimmten Bus. Ein Vergleich, der diese Unterschiede außer Acht lässt, stellt somit Ansätze nebeneinander, die sich gegenseitig gar nicht ersetzen können. Im abschließenden Vergleich wird die Ebene deshalb in einer eigenen Spalte ausgewiesen.

Diese Kriterien strukturieren die folgende Betrachtung und münden in den abschließenden Vergleich in @tab:vergleich.

== Etablierte Rahmenwerke für entfernte Aufrufe

Entfernte Prozeduraufrufe wurden früh standardisiert. Der @onc_rpc @microsystemsRPCRemoteProcedure1988 legt ein Protokoll und mit der External Data Representation ein eigenes Serialisierungsformat fest @thurlowRPCRemoteProcedure2009. Der Ansatz ist auf leistungsfähigere Netzwerke ausgelegt und nicht für Kanäle mit Paketgrößen im Bereich weniger Byte gedacht.

JSON-RPC verfolgt eine deutlich schlankere Idee @JSONRPC20Specification, da die Spezifikation ausschließlich das Format der Anfrage- und Antwortnachrichten auf Basis von @json beschreibt und den Transport bewusst der Anwendung überlässt. Diese Trennung ist dem hier verfolgten Ansatz ähnlich, allerdings setzt JSON-RPC voraus, dass eine darunterliegende Schicht vollständige Nachrichten zustellen kann. Es definiert weder eine Rahmung noch eine Fragmentierung für sehr kleine Pakete und sieht keinen Mechanismus für einen anfragegetriebenen Rückkanal auf einem Master-Slave-Bus vor.

Am anderen Ende des Spektrums steht @g_RPC @GRPC. Das Rahmenwerk verbindet Protocol Buffers als schemagebundene Serialisierung mit @http/2 als Transport und unterstützt unter anderem Datenströme in beide Richtungen. Diese Leistungsfähigkeit erfordert jedoch einen vollständigen @http/2-Stack und setzt eine bidirektionale Verbindung voraus. Für den betrachteten LEGO-Bus und die eingesetzten Laufzeitumgebungen ist @g_RPC zu schwergewichtig und zu stark an seinen Transport gebunden.

Näher an der hier betrachteten Geräteklasse liegen zwei jüngere Ansätze. eRPC @IntroducingERPC2017 überträgt entfernte Aufrufe zwischen Mikrocontrollern über @uart, @spi oder @i2c und bringt dafür eine eigene Rahmung mit. Der Aufruf wird allerdings aus einer Schnittstellenbeschreibung erzeugt, das heißt die aufrufbaren Funktionen stehen zur Übersetzungszeit fest, und ein Objektmodell mit zur Laufzeit erzeugten Referenzen ist nicht vorgesehen. DDS-XRCE @DDSExtremelyResource richtet sich an sehr kleine Geräte, arbeitet über einen vermittelnden Agenten und fragmentiert dabei auch über serielle Verbindungen. Eingesetzt wird es etwa von micro-ROS, das ROS 2 auf Mikrocontroller überträgt und dort einen in C geschriebenen Client über einen Agenten auf einem leistungsfähigeren Rechner anbindet @microROSAgent. Der Client stößt jede Übertragung an, was dem hier betrachteten Rückkanal entspricht. Beiden gemeinsam ist, dass die Schnittstelle vorab beschrieben und daraus Code erzeugt wird. Was aufgerufen werden kann, steht damit vor dem Start fest.

Zusammengefasst setzen die etablierten Rahmenwerke entweder einen leistungsfähigen Transport voraus oder standardisieren nur die Nachrichtenebene. Rahmung, Fragmentierung und der Rückkanal bleiben dann offen, und genau diese darunterliegende Schicht behandelt die vorliegende Arbeit.

== Serialisierung für ressourcenarme Geräte <sec:serialisierung-geraete>

Da die Serialisierung die Nachrichtengröße und damit die Anzahl der nötigen Pakete bestimmt, ist sie für ein System mit kleinen Paketen besonders relevant. @json ist schemafrei und gut lesbar, erzeugt aber durch Klartextschlüssel und Strukturzeichen vergleichsweise große Ausgaben @brayJavaScriptObjectNotation2017. Binäre und schemafreie Formate wie MessagePack @MessagePackItsJSON und die @cbor @bormannConciseBinaryObject2020 @CBORConciseBinary erreichen bei gleichem Datenmodell deutlich kompaktere Darstellungen. Schemagebundene Formate wie Protocol Buffers gehen noch einen Schritt weiter und setzen eine geteilte Beschreibung der Datenstruktur voraus @ProtocolBuffers. Für sehr kleine Geräte existiert mit Nanopb @NanopbZephyrProject eine ressourcenschonende Implementierung dieses Ansatzes. Welches dieser Formate die Referenzimplementierung verwendet, warum sie zunächst ein anderes benutzte und was der Wechsel gekostet hat, beschreibt @sec:umsetzung-codec.

== Protokolle für eingebettete Systeme und Sensornetze

Neben den allgemeinen Rahmenwerken existieren Protokolle, die näher an der betrachteten Domäne liegen. Firmata @FirmataArduino2026 ermöglicht die Steuerung eines Mikrocontrollers von einem übergeordneten Rechner aus und überträgt dazu einen festgelegten Satz von Befehlen über eine serielle Verbindung. Die Aufteilung in einen steuernden Rechner und ein reagierendes Gerät ähnelt der hier vorliegenden Situation. Firmata beschränkt sich allerdings auf einen vordefinierten Befehlsumfang und bietet weder einen allgemeinen entfernten Aufruf noch eine Abstraktion entfernter Objekte.

@mqtt @MQTTStandardIoT ist auf ressourcenarme Geräte und kleine Pakete ausgelegt und kommt ohne eine durchgehende @tcp\-Verbindung aus. Es folgt jedoch einem Modell aus Veröffentlichen und Abonnieren, benötigt ein Gateway sowie einen Vermittler und setzt voraus, dass das Gerät eigenständig veröffentlichen kann. Auf einem Bus, auf dem die übergeordnete Seite von Daten erst beim Nachfragen erfährt, ist dieses Modell nicht unmittelbar anwendbar.

Näher am hier betrachteten Problem liegen Protokolle, die eine Nachricht über mehrere kleine Pakete hinweg übertragen und dabei ohne eine darunterliegende Transportschicht auskommen. Das Transportprotokoll ISO 15765-2, im Fahrzeugbereich als ISO-TP bekannt, überträgt Nachrichten von bis zu 4095 Byte über CAN-Rahmen mit acht Byte Nutzlast @DINMediaStandards. Es nummeriert die Folgerahmen fortlaufend und lässt den Empfänger im Flusskontrollrahmen angeben, wie viele Rahmen er am Stück annimmt. Die Aufgabenstellung entspricht damit weitgehend der Rahmung und Fragmentierung dieser Arbeit, allerdings bleibt ISO-TP auf den Transport beschränkt und kennt weder Aufrufe noch entfernte Objekte.

Ein ähnliches Vorgehen findet sich in CANopen, wo das Service Data Object Datensätze segmentiert überträgt, die größer sind als ein einzelner CAN-Rahmen @CANopen. Dort wird zudem jeder Segmentabschnitt einzeln bestätigt, was dem Stop-and-Wait dieser Arbeit entspricht. Die adressierten Daten sind jedoch Einträge eines vorab festgelegten Objektverzeichnisses und keine zur Laufzeit erzeugten Objekte mit eigenen Methoden.

Im Umfeld ressourcenarmer Geräte löst @coap dieselbe Aufgabe auf Anwendungsebene @shelbyConstrainedApplicationProtocol2014. Der Block-wise Transfer aus RFC 7959 zerlegt eine Repräsentation in nummerierte Blöcke, deren Größe zwischen 16 und 1024 Byte ausgehandelt wird, und überträgt jeden Block mit einer eigenen Anfrage des Clients @bormannBlockWiseTransfersConstrained2016. Damit ist der Ansatz dem hier entwickelten Rückkanal sehr ähnlich, denn auch dort fordert der Client jeden Block einzeln an. Die kleinste vorgesehene Blockgröße liegt allerdings bereits über der Nutzlast, die der betrachtete Bus je Paket zulässt, und @coap setzt einen Datagrammdienst wie @udp voraus.

Am nächsten an der Aufgabe dieser Arbeit liegen serielle Displays mit eigener Oberflächenlogik, etwa die Module von Nextion @nextionInstructionSet. Seiten und Bedienelemente werden dort vorab in einem Editor entworfen und auf dem Display abgelegt. Der Host spricht sie anschließend über Textbefehle mit ihrem Namen an, wobei jeder Befehl mit drei Bytes `0xFF` abschließt. Auf Ereignisse reagiert das Display mit eigenem Code, der auch Bedingungen und Schleifen enthalten darf, sich aber nicht über die serielle Verbindung übertragen lässt. Das entspricht dem Objektmodell zusammen mit den Bindings dieser Arbeit, allerdings mit einer festen, herstellereigenen Befehlssprache und einer Oberfläche, die nicht zur Laufzeit entsteht, sondern vorab feststeht.

Diese Protokolle liegen nah an der betrachteten Domäne, lösen aber jeweils einen Teil der Aufgabe. Sie zielen auf Gerätesteuerung mit festem Befehlssatz, auf vorab entworfene Oberflächen, auf nachrichtenbasiertes Veröffentlichen und Abonnieren oder auf die segmentierte Übertragung von Daten. Einen allgemeinen, objektorientierten entfernten Aufruf über einen anfragegetriebenen Kanal mit Paketen von wenigen Byte bietet keines von ihnen.

== Der betrachtete Bus und PUPRemote als Transportbasis

Der Hub und die angeschlossenen Geräte verkehren über @lpf2, ein Protokoll, das auf einer @uart\-Verbindung über die Sensorports aufsetzt @LeJOSEV3Wiki. Der Hub ist dabei der Master. Ein Gerät meldet sich beim Anstecken mit den Modi an, die es unterstützt. Jeder Modus beschreibt einen Kanal mit festem Namen, fester Länge und festem Datentyp. Der Hub wählt einen dieser Modi aus und liest dessen Wert oder schreibt einen Wert hinein.

PUPRemote @PUPRemoteDocumentationAntons nimmt in diesem Umfeld eine Sonderstellung ein, da es in dieser Arbeit als Baustein der eigenen Lösung eingesetzt wird. Die Bibliothek erschließt den @pup\- und @lpf2\-Bus und stellt darauf benannte Aufrufe bereit. Jeder Aufruf belegt einen eigenen Modus des Busses und ist über feste Formatangaben für beide Richtungen beschrieben. Der Hub schreibt die Argumente in den zugehörigen Modus und liest anschließend den Rückgabewert aus demselben Modus zurück. Mit PUPRemote werden auf beiden Seiten Befehle registriert, die anschließend vom Master aufgerufen werden können. Die Länge der Befehlsnamen, der Argumente und der Rückgabewerte ist dabei durch die festen Formatangaben begrenzt. PUPRemote besitzt damit durchaus eine eigene Aufrufsemantik und ist nicht auf reinen Datentransport beschränkt.

Diese Semantik trägt jedoch nur so weit, wie sich ein Aufruf auf einen vorab registrierten Modus und ein einzelnes Paket fester Größe abbilden lässt. Die Anzahl der Modi ist durch den Bus begrenzt, die Formate stehen zur Übersetzungszeit fest, und für Nachrichten, die größer sind als ein Paket, ist kein Mechanismus vorgesehen. Eine Middleware, die beliebige Methoden auf einer zur Laufzeit wachsenden Menge entfernter Objekte anbieten soll, kann daher nicht einen Modus je Aufruf vergeben.

Die vorliegende Arbeit nutzt PUPRemote deshalb nur als Busanbindung. Registriert wird ein einziges Kommando, dessen Nutzlast aus Sicht von PUPRemote ein Block fester Länge ohne Struktur ist. Die Zerlegung von Nachrichten in Pakete, deren Rahmung, die Zuordnung von Antworten zu Anfragen, der anfragegetriebene Rückkanal sowie das Objektmodell aus Stellvertretern und serverseitigen Adaptern liegen vollständig darüber. PUPRemote übernimmt damit die Rolle der Busanbindung und kann durch andere Bibliotheken ersetzt werden, die denselben Austausch von Blöcken leisten.

== Abgrenzung

@tab:vergleich fasst die betrachteten Ansätze entlang der eingangs definierten Kriterien zusammen.

#figure(
  caption: [Vergleich der betrachteten Ansätze entlang der Auswahlkriterien],
  text(size: 7.5pt)[
    #table(
      columns: (0.9fr, 1fr, 1.2fr, 1.1fr, 1.1fr, 0.8fr, 1.1fr, 0.9fr),
      align: left + top,
      table.header(
        [*Ansatz*], [*Ebene*], [*Abstraktionsgrad*], [*Serialisierung*], [*Transportbindung*], [*Fragmentierung*], [*Eignung kleiner Master-Slave-Bus*], [*MicroPython und Pybricks*],
      ),
      [@g_RPC], [Middleware], [@rpc und Datenströme], [Protocol Buffers, schemagebunden], [an @http/2 gebunden], [über @http/2], [ungeeignet, setzt Push voraus], [nein, kein @http/2],
      [JSON-RPC], [Nachrichtenformat], [nur Nachrichtenformat], [@json, textbasiert], [unabhängig, offen], [nicht definiert], [offen, Rückkanal fehlt], [ja, `ujson` vorhanden],
      [MessagePack und @cbor], [Serialisierung], [nur Serialisierung], [binär, schemafrei], [entfällt], [entfällt], [entfällt], [ja, mit eigener Umsetzung],
      [Firmata], [Geräteprotokoll], [Gerätesteuerung mit festen Befehlen], [binär, fest], [seriell, fest], [nein], [passend, aber fester Befehlssatz], [nein, Geräteseite in C],
      [ISO-TP], [Transportprotokoll], [nur Transport], [entfällt], [an CAN gebunden], [ja, bis 4095 Byte], [passend, aber ohne Aufrufe], [entfällt, kein CAN],
      [CANopen SDO], [Geräteprotokoll], [Zugriff auf ein Objektverzeichnis], [feste Einträge], [an CAN gebunden], [ja, segmentiert], [passend, aber festes Verzeichnis], [entfällt, kein CAN],
      [@coap Block-wise], [Anwendungsprotokoll], [@rest\-artiger Zugriff], [binär, schemafrei], [setzt @udp voraus], [ja, ab 16 Byte], [Blockgröße zu groß], [nein, kein @udp],
      [@mqtt], [Nachrichtenprotokoll], [Veröffentlichen und Abonnieren], [binär, kompakt], [unabhängig, braucht Gateway], [teilweise], [setzt eigenständiges Senden voraus], [nein, kein Netzwerkstack],
      [eRPC], [Middleware], [entfernter Aufruf, Schnittstelle zur Übersetzungszeit], [eigenes Format, schemagebunden], [austauschbar, seriell möglich], [ja], [passend, aber ohne Objektmodell], [nein, C-Werkzeugkette],
      [DDS-XRCE], [Middleware], [Datenaustausch über einen Agenten], [binär, schemagebunden], [austauschbar, seriell möglich], [ja], [passend, aber Agent nötig], [nein, C-Bibliothek],
      [PUPRemote], [Transportanbindung, hier als Baustein verwendet], [entfernter Aufruf, ein Modus je Aufruf], [feste Formatangaben je Modus], [an @pup und @lpf2 gebunden], [nein, ein Paket], [passend, aber nur ein Paket], [ja],
      [Diese Arbeit], [Middleware], [entfernter Aufruf und entfernte Objekte], [MessagePack, gekapselt und austauschbar], [gekapselt, PUPRemote als erste Bindung], [ja, eingebaut], [passend, anfragegetriebener Rückkanal], [ja],
    )
  ],
) <tab:vergleich>

Aus dem Vergleich wird die Lücke deutlich, die diese Arbeit schließt. Sie ist als Ergebnis der hier getroffenen Auswahl zu lesen und nicht als Aussage über den gesamten Stand der Technik, denn dafür wäre eine systematische Recherche nötig, die den Rahmen einer Projektarbeit überschreitet. Die leistungsfähigen Rahmenwerke setzen einen Transport voraus, den das Zielsystem nicht bietet. Die schlanken Ansätze standardisieren nur Teilaspekte und lassen Rahmung, Fragmentierung und den Rückkanal offen. Die domänennahen Protokolle lösen eine andere Aufgabe oder setzen voraus, dass die untergeordnete Seite eigenständig zustellen kann. Am nächsten kommen eRPC und DDS-XRCE, die beide für Mikrocontroller und serielle Verbindungen gedacht sind. Sie verlangen jedoch eine zur Übersetzungszeit festgelegte Schnittstelle und eine Werkzeugkette, die auf den hier eingesetzten Laufzeitumgebungen nicht zur Verfügung steht, und sie bieten kein Objektmodell, dessen Referenzen zur Laufzeit entstehen. PUPRemote liegt schließlich eine Ebene tiefer. Es erschließt den Bus und wird in dieser Arbeit als Busanbindung genutzt, ersetzt aber nicht die gesuchte Middleware.

Die vorliegende Arbeit verbindet diese Aspekte zu einer zusammenhängenden Lösung. Sie stellt einen transportunabhängig entworfenen entfernten Aufruf samt Objektmodell bereit, bringt Rahmung und Fragmentierung für sehr kleine Pakete mit und setzt einen anfragegetriebenen Rückkanal für einen Master-Slave-Bus um. All das läuft innerhalb der Grenzen von MicroPython und Pybricks. Der Beitrag liegt damit weniger in einem einzelnen neuen Baustein als in der Kombination bekannter Konzepte für einen Anwendungsfall, den keiner der betrachteten Ansätze abdeckt.